### ISSUE TITLE
Bug: UI exception in Artemis.Plugins.Devices.YeeLight while opening settings

### ISSUE THREAD

**Issue by dmaniaa** [Cheerpipe/Artemis.Plugins.Public#4]
An exception occurs when opening settings for YeeLight plugin.

Artemis version: 2.0-935c13 build 20220205.1
Plugin version: latest available at https://nightly.link/Cheerpipe/Artemis.Plugins.Public/workflows/plugins/master/Artemis.Plugins.Devices.YeeLight

Stack trace:
`Stylet.StyletViewLocationException: Unable to find a View with type Artemis.Plugins.Devices.YeeLight.Views.YeeLightConfigurationDialogView
   at Stylet.ViewManager.LocateViewForModel(Type modelType)
   at Stylet.ViewManager.CreateViewForModel(Object model)
   at Stylet.ViewManager.CreateAndBindViewForModel(Object model)
   at Stylet.ViewManager.OnModelChanged(DependencyObject targetLocation, Object oldValue, Object newValue)
   at Stylet.Xaml.View.<>c.<.cctor>b__10_0(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.Activate(Object item)
   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)
   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)
   at MS.Internal.Data.DataBindEngine.Run(Object arg)
   at MS.Internal.Data.DataBindEngine.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Interop.HwndSource.set_RootVisual(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at Stylet.WindowManager.ShowWindow(Object viewModel, IViewAware ownerViewModel)
   at Stylet.WindowManager.ShowWindow(Object viewModel)
   at Artemis.UI.Screens.Settings.Tabs.Plugins.PluginSettingsViewModel.OpenSettings() in D:\a\1\s\Artemis\src\Artemis.UI\Screens\Settings\Tabs\Plugins\PluginSettingsViewModel.cs:line 102`

Steps to repro:
1. Open specified version of Artemis
2. Go into the settings section
3. Go into the plugins tab
4. Select Import plugins
5. Select file with specified version of the plugin
6. Select Plugin enabled for the YeeLight Devices plugin
7. Click on Settings

Expected result: Settings menu opens
Actual result: Artemis shows an exception window with aforementioned exception.

**Comment by Rival** [comment]
@dmaniaa I got similar exception. It was fixed in the master branch.

**Comment by dmaniaa** [comment]
Confirmed. The bug does not reproduce for me neither on the latest nightly build from master. Closing the issue as fixed.
